### ISSUE TITLE
Compatibility error with Let's Do Meadow mod makes negative durability watering can crash the game

### ISSUE THREAD

**Issue by VisigothiCheeta** [Commoble/useitemonblockevent#1]
# Game version:
1.20.1 (Forge 47.2.17)

# Mods loaded:

architectury-9.2.14-forge.jar
letsdo-API-forge-1.2.9-forge.jar
letsdo-meadow-forge-1.3.8.jar
morered-1.20.1-4.0.0.4.jar

# How to reproduce: 

<details>
<summary>Get a negative durability watering can from Meadow on survival mode;</summary>
(this happened naturally as the Meadow mod was updated and its durability cap was nerfed)
</details>
Use it on a grass block.
(this does not happen if the game runs without morered)

# Relevant crash log chunks:

java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=damage, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5]} to 100 on Block{meadow:watering_can}, it is not an allowed value

[...]

Thread: Render thread
Suspected Mods:

	[Let's Do] Meadow (meadow), Version: 1.3.8
		at TRANSFORMER/meadow@1.3.8/net.satisfyu.meadow.item.WateringCanItem.m_5965_(WateringCanItem.java:180)

	More Red (morered), Version: 4.0.0.4
		Issue tracker URL: https://github.com/Commoble/morered/issues
		at TRANSFORMER/morered@**.**.**.**/commoble.morered.MoreRed.onUseItemOnBlock(MoreRed.java:471)

	Use Item on Block Event (useitemonblockevent), Version: 1.0.0.2
		Issue tracker URL: https://github.com/Commoble/useitemonblockevent/issues
		at TRANSFORMER/useitemonblockevent@**.**.**.**/commoble.useitemonblockevent.internal.MixinCallbacks.fireUseItemOnBlock(MixinCallbacks.java:43)
		
# Note
To save you some time, I believe "at TRANSFORMER/meadow@1.3.8/net.satisfyu.meadow.item.WateringCanItem.m_5965_(WateringCanItem.java:180)" refers to the following lines of code in the watering can's source code:

    protected BlockState getPlacementState(BlockPlaceContext blockPlaceContext) {
        BlockState state = super.getPlacementState(blockPlaceContext);
        if(state != null) state = state.setValue(WateringCanBlock.DAMAGE, blockPlaceContext.getItemInHand().getDamageValue());
        return state;
    }

**Comment by Commoble** [comment]
does the crash happen without useitemonblockevent

**Comment by VisigothiCheeta** [comment]
Yes it does. I should have made this thread on MoreRed's repository, but the URL in the crash log sent me here.

Adding useitemonblockevent to the mods fixed the issue when using these mods only, is it a dependency?

But I had isolated these mods to test what was causing the issue, using my entire modpack it now says Create is causing this crash:

        Suspected Mod: 
	Create (create), Version: 0.5.1.f
		Issue tracker URL: https://github.com/Creators-of-Create/Create/issues
		at TRANSFORMER/create@0.5.1.f/com.simibubi.create.foundation.events.ClientEvents.onTick(ClientEvents.java:137)
		
Maybe Meadow is actually the mod causing the issue? I'll test if doing this with only Meadow and Create+addons causes the game to crash.

**Comment by VisigothiCheeta** [comment]
I tested and no, the game didn't crash with architectury, letsdoAPI, meadow and create+addons loaded only.

Running with only architectury, letsdoAPI, meadow, create+addons and useitemonblockevent (without morered) crashed the game but for some reason only on the second time I used the watering can on a grass block and it was on creative mode (until now it had only crashed on survival mode). If this didn't happen I'd close this thread and open another at MoreRed.

Then I tried running my entire modpack but without both MoreRed and useitemonblockevent and it does not crash the game, so the bug seems to be related to them directly.
EDIT: I kept spamming the watering can after posting this and it crashed eventually, this time blaming BetterThirdPerson on the logs.
EDIT2: Tried spamming the negative durability watering can with all the mods loaded except MoreRed, useitemonblockevent and BetterThirdPerson, hasn't crashed.

**Comment by Commoble** [comment]
If you just have meadow and no other mods, and shift-right-click a block with a watering can with an invalid damage value, does it crash?

**Comment by VisigothiCheeta** [comment]
No.

**Comment by Commoble** [comment]
well, in any case, the problem is this piece of code in meadows doesn't validate the damage value

```java
    @Nullable
    @Override
    protected BlockState getPlacementState(BlockPlaceContext blockPlaceContext) {
        BlockState state = super.getPlacementState(blockPlaceContext);
        if(state != null) state = state.setValue(WateringCanBlock.DAMAGE, blockPlaceContext.getItemInHand().getDamageValue());
        return state;
    }
```

So, presumably meadow is validating the damage value elsewhere (otherwise it would crash on its own), but any mod that tries to get the placement state from a blockitem in order to simulate anything will cause invalid watering cans to crash (more red trips over this because it checks whether the block being placed would intersect with nearby wires).

The best fix would be for meadows to validate the damage value of the item in getPlacementState and make sure it's not setting invalid values in the blockstate.
